### ISSUE TITLE
Request page build

### ISSUE THREAD

**Issue by swinton** [Carlgo11/TempFiles#6]
1. https://developer.github.com/v3/repos/pages/#request-a-page-build
1. https://github.com/octokit/request-action

**Comment by Carlgo11** [comment]
That worked. Thanks for your help Steve! :smile: 
For reference, here's the working gh action YAML: [deploy.yml](https://github.com/Carlgo11/TempFiles/blob/f363ce1b140817b90d19c791ccb333ae70a8e044/.github/workflows/deploy.yml)

**Comment by swinton** [comment]
Awesome! Glad it’s working for you! 🚀
